var data = {
	action: [
		"Characters as Device",
		"Chase Scene",
		"Cut to the Index",
		"Death Trap",
		"Distraction Tropes",
		"Dream Tropes",
		"Ending Tropes",
		"Episodes",
		"Escape Tropes",
		"Fight Scene",
		"Flashbacks and Chronology",
		"Index All Along",
		"Luke, I Am Your Index",
		"MacGuffin",
		"Montages",
		"Movie Twist List",
		"Plot Twist",
		"Room Shuffle",
		"Scenes",
		"Short Con",
		"Sleep And Wakefulness Tropes",
		"Stock Puzzle",
		"Stock Superpowers",
		"The Tale",
		"Twist Ending",
		"That Which Must Not Be Indexed",
		"You Hate What You Are",
		"Absurdly High Stakes Game",
		"Accidental Bid",
		"Adults Are Useless",
		"Affair Hair",
		"A Fool for a Client",
		"Aliens Are Bastards",
		"All Just a Dream",
		"Always Need What You Gave Up",
		"Amnesiac Dissonance",
		"Androcles Lion",
		"And Your Little Dog Too",
		"Anti Mutiny",
		"Apocalypse Not",
		"Arc Welding",
		"Arc Number",
		"Arc Symbol",
		"Arc Words",
		"Art Imitates Art",
		"Attending Your Own Funeral",
		"Authentication By Newspaper",
		"Author Avatar",
		"Avengers Assemble",
		"Awesome Moment of Crowning",
		"Awful Truth",
		"Axe Before Entering",
		"Backstab Backfire",
		"Bad Date",
		"Bad Luck Charm",
		"Bags of Letters",
		"Barn Raising",
		"Batman Grabs a Gun",
		"Bathroom Break-Out",
		"Bathroom Stall Graffiti",
		"Battle Royale With Cheese",
		"Beat Them at Their Own Game",
		"Bedsheet Ladder",
		"Belly of the Whale",
		"Best For Last",
		"Better to Die than Be Killed",
		"Beverage Spill",
		"Big Blackout",
		"The Big Bad Shuffle",
		"The Big Damn Kiss",
		"Big Dumb Object",
		"Big Ego Hidden Depths",
		"Big Heroic Run",
		"Blessed with Suck",
		"Blitz Evacuees",
		"Big Brother Is Employing You",
		"Big Brother Is Watching",
		"Big Shadow, Little Creature",
		"Body Count Competition",
		"Bolivian Army Cliffhanger",
		"Bothering By The Book",
		"Bonding Over Missing Parents",
		"Bound and Gagged",
		"A Boy and His X",
		"Boxing Lesson",
		"Boy Meets Girl",
		"Break The Fake",
		"Breaking the Fellowship",
		"Breaking the Fourth Wall",
		"Broken Glass Penalty",
		"Brown Note",
		"Buried Treasure",
		"Burn the Witch!",
		"But I Digress",
		"Butterfly of Doom",
		"Call On Me",
		"Camp Unsafe Isn't Safe Anymore",
		"Can't Stay Normal",
		"Cardboard Prison",
		"Carrying a Cake",
		"Caught in the Rain",
		"Cassandra Truth",
		"Catapult Nightmare",
		"Caught On Tape",
		"Celebrity Star",
		"Cell Phone",
		"Chained Heat",
		"Chain of Deals",
		"Chair Reveal",
		"Chance Activation",
		"Chariot Race",
		"A Chat With Satan",
		"Cheating With The Milkman",
		"Childhood Memory Demolition Team",
		"Clark Kenting",
		"Class Trip",
		"Cliff Hanger",
		"Bolivian Army Cliffhanger",
		"Cliffhanger Copout",
		"What Cliffhanger",
		"The Climax",
		"Climbing Climax",
		"Clingy MacGuffin",
		"Coincidental Broadcast",
		"Cold-Blooded Torture",
		"Cold Turkeys Are Everywhere",
		"Collective Identity",
		"Come to Gawk",
		"Come With Me If You Want To Live",
		"Complaining About Rescues They Don't Like",
		"Confessional",
		"Conflicting Loyalty",
		"Conservation of Competence",
		"Contemplate Our Navels",
		"Continuity Cavalcade",
		"Continuity Nod",
		"Continuity Cameo",
		"Contractual Gag",
		"Contrived Coincidence",
		"Convenient Eclipse",
		"Conveniently Common Kink",
		"Conveniently Seated",
		"Cool and Unusual Punishment",
		"The Coroner Doth Protest Too Much",
		"Cosmic Retcon",
		"Couldn't Find A Pen",
		"Counting Sheep",
		"Courtroom Antic",
		"Crack Defeat",
		"Crashing Dreams",
		"Cross Over",
		"Fake Cross Over",
		"Critical Failure",
		"Critical Psychoanalysis Failure",
		"Crowd Chant",
		"Crowd Song",
		"Spontaneous Choreography",
		"Crowd Panic",
		"Cruel Mercy",
		"Cryptic Background Reference",
		"Crystal Ball Scheduling",
		"Cursed with Awesome",
		"Curse Is Foiled Again",
		"Cutting The Electronic Leash",
		"Dance Line",
		"Dark Horse Victory",
		"Darkened Building Shootout",
		"Darkest Hour",
		"Darkness Equals Death",
		"Dating Service Disaster",
		"The Day Of Reckoning",
		"Dead End Job",
		"Dead ex Machina",
		"Dead Partner",
		"Dead Person Conversation",
		"Dead Sidekick",
		"Deadly Graduation",
		"Debut Queue",
		"Decapitated Army",
		"Decision Darts",
		"Decoy Getaway",
		"Defusing the Tyke Bomb",
		"Depth Deception",
		"Deus Est Machina",
		"Deus Exit Machina",
		"Deus ex Machina",
		"Deuteragonist",
		"Did You Just Flip Off Cthulhu?",
		"Did We Just Have Tea with Cthulhu?",
		"Discontinuity Nod",
		"Disguised in Drag",
		"Dismantled MacGuffin",
		"Diving Save",
		"Documentary Episode",
		"Do Not Go Gentle",
		"Don't Ask, Just Run",
		"Don't Celebrate Just Yet",
		"Don't Split Us Up",
		"Doomed Hometown",
		"Door Jam",
		"Doorstop Baby",
		"Double Date",
		"Drama Bomb",
		"Dramatic Curtain Toss",
		"Dramatic Dislocation",
		"Dramatic Irony",
		"Dream Land",
		"Dream Within a Dream",
		"Dream Sequence",
		"Driving Question",
		"Driving Test Smashers",
		"Dug In Deeper",
		"Dungeon Bypass",
		"Drunk On The Dark Side",
		"Dueling Hackers",
		"Dying Like Animals",
		"Dysfunction Junction",
		"Earth All Along",
		"Earth-Shattering Kaboom",
		"Easily Forgiven",
		"Eat The Dog",
		"Eat The Evidence",
		"Egg MacGuffin",
		"Either-Or Prophecy",
		"Electrified Bathtub",
		"Elves Versus Dwarves",
		"Emergency Presidential Address",
		"Empathic Weapon",
		"Empty Cop Threat",
		"Endangered Soufflé",
		"Enforced Cold War",
		"Engagement Challenge",
		"Engineered Public Confession",
		"Epic Fail",
		"Epiphanic Prison",
		"The Eternal Churchill",
		"Et Tu, Brute?",
		"Even the Dog Is Ashamed",
		"Everybody's Dead, Dave",
		"Everyone Knows Morse",
		"The Evils of Free Will",
		"Evil Phone",
		"Evil Plan",
		"Exact Eavesdropping",
		"Exact Words",
		"Expansion Pack World",
		"Expendable Clone",
		"Explaining The Soap",
		"Explosive Leash",
		"Explosion Propulsion",
		"Extremely Short Timespan",
		"Eye Remember",
		"Failed a Spot Check",
		"Failure Is the Only Option",
		"Fainting Seer",
		"Fake Defector",
		"Fake Static",
		"Fall of the House of Cards",
		"Fancy Dinner",
		"Fascists' Bed Time",
		"Faustian Rebellion",
		"Faux Death",
		"Fauxlosophic Narration",
		"Fauxshadow",
		"Feet of Clay",
		"Fence Painting",
		"Fiction Isn't Fair",
		"Field Promotion",
		"Fighting For Survival",
		"Fisher King",
		"Final Exam Finale",
		"Five Second Foreshadowing",
		"Fling A Light Into The Future",
		"Flying Dutchman",
		"Food Chains",
		"Follow The White Rabbit",
		"Forbidden Fruit",
		"Forced Prize Fight",
		"Foreigner For A Day",
		"Foreshadowing",
		"Found Footage Films",
		"The Four Loves",
		"Framed Clue",
		"Frameup",
		"Framing the Guilty Party",
		"Framed For Heroism",
		"Frantic Object Concealment",
		"Freak Out",
		"Freaky Friday Flip",
		"Friend or Idol Decision",
		"Friends All Along",
		"Frothy Mugs of Water",
		"Fur Against Fang",
		"Future Badass",
		"Gambit Pileup",
		"Genocide Dilemma",
		"Geodesic Cast",
		"George Jetson Job Security",
		"George Washington Slept Here",
		"Generic Graffiti",
		"Get Out Of Jail Free Card",
		"Getting Hot in Here",
		"Give Me a Sign",
		"Give Me Liberty Or Give Me Death",
		"Go Among Mad People",
		"Go Back To The Source",
		"A God Am I",
		"Godzilla Threshold",
		"Going In Circles",
		"Going to See the Elephant",
		"Going Postal",
		"Golden Moment",
		"Golden Snitch",
		"Gossip Evolution",
		"Got Volunteered",
		"Grail In The Garbage",
		"Green Rooming",
		"Guess Who I'm Marrying?",
		"Hannibal Lecture",
		"Happier Home Movie",
		"Harmful to Minors",
		"Haunted Headquarters",
		"He Had It Coming",
		"Heat Wave",
		"Heart Trauma",
		"Heel Realization",
		"Hell On Earth",
		"Here We Go Again",
		"Heroic Vow",
		"Hidden in Plain Sight",
		"High Turnover Rate",
		"History Repeats",
		"Holding Out for a Hero",
		"Holding The Floor",
		"Homage",
		"Hope Springs Eternal",
		"Hostage for MacGuffin",
		"Hostage Situation",
		"Hostile Weather",
		"Hourglass Plot",
		"How Did We Get Back Home?",
		"How Much Did You Hear?",
		"Human Ladder",
		"Human Resources",
		"Human Shield",
		"Humble Pie",
		"Humiliation Conga",
		"I Am He as You Are He",
		"I Am One Of Those Too",
		"I Do Not Like Green Eggs and Ham",
		"Ignored Vital News Reports",
		"I Hate You, Vampire Dad",
		"I Have Your Wife",
		"I Just Want To Be Badass",
		"I Just Want to Be Normal",
		"I Just Want to Be Special",
		"\"I Know What We Can Do\" Cut",
		"I Never",
		"Internalized Categorism",
		"Intrepid Fictioneer",
		"Invisible Subtle Difference",
		"I Owe You My Life",
		"The Ishmael",
		"I See Them Too",
		"Identical Grandson",
		"If I Can Only Move",
		"If You Won't, I Will",
		"Impossible Task",
		"I'm A Humanitarian",
		"Inadvertent Entrance Cue",
		"Innocent Inaccurate",
		"Innocent Innuendo",
		"Instant Expert",
		"Insulted Awake",
		"Internal Homage",
		"Intercontinuity Crossover",
		"Interrogation By Vandalism",
		"Interrogating the Dead",
		"Interrupted Suicide",
		"Intimidating Revenue Service",
		"Invisible to Adults",
		"Invisible to Normals",
		"Irrevocable Message",
		"Is This Thing Still On?",
		"It Must Be Mine",
		"It's All Junk",
		"It's The Journey That Counts",
		"It's Probably Nothing",
		"It Was a Gift",
		"It Was With You All Along",
		"I Was Having Such a Nice Dream",
		"I Will Find You",
		"Jacob Marley Warning",
		"Jail Bake",
		"Jeopardy! Intelligence Test",
		"Joker Jury",
		"Jury Of The Damned",
		"Keep The Reward",
		"Kent Brockman News",
		"The Key Is Behind the Lock",
		"Kicked Upstairs",
		"Kidnapped By An Ally",
		"Knife Throwing Act",
		"Knights and Knaves",
		"Lamaze Class",
		"Leaning on the Fourth Wall",
		"Least Is First",
		"Leave Him to Me",
		"Leave the Camera Running",
		"Leonine Contract",
		"Leno Device",
		"Lethally Expensive",
		"A Light in the Distance",
		"Limited Destination Time",
		"List Of Transgressions",
		"The Little Shop That Wasn't There Yesterday",
		"Living a Double Life",
		"Living on Borrowed Time",
		"Living With The Villain",
		"Locked in a Freezer",
		"Locked in a Room",
		"Locked Out of the Fight",
		"Locking MacGyver in the Store Cupboard",
		"Look Ma No Plane",
		"Loser Gets The Girl",
		"Lowered Monster Difficulty",
		"Luke, I Am Your Father",
		"Luke, You Are My Father",
		"Lured Into A Trap",
		"MacGuffin",
		"MacGuffin Delivery Service",
		"MacGuffin Location",
		"Made Of Temptation",
		"Magic Hat",
		"Magical Girl Queenliness Test",
		"Magnetic Plot Device",
		"The Main Characters Do Everything",
		"Major Injury Underreaction",
		"Make a Wish",
		"Manufacturing Victims",
		"Marketeers Vs Engineers",
		"Mating Dance",
		"Meaningful Echo",
		"Medal of Dishonor",
		"Melodramatic Pause",
		"Memento MacGuffin",
		"Mercy Lead",
		"Message in a Bottle",
		"A Mind Is a Terrible Thing to Read",
		"Mind Rape",
		"Mind Screwdriver",
		"Mineral MacGuffin",
		"Minor Flaw, Major Breakup",
		"Miracle Rally",
		"Miranda Rights",
		"Misfit Mobilization Moment",
		"Mistaken for Badass",
		"Mistaken Identity",
		"Mister Sandman Sequence",
		"Mistimed Revival",
		"Mood Whiplash",
		"Morton's Fork",
		"Moses in the Bullrushes",
		"Mundane Solution",
		"Mushroom Samba",
		"Must Have Nicotine",
		"Mutilation Interrogation",
		"The Mutiny",
		"My Fist Forgives You",
		"My Greatest Failure",
		"My Greatest Second Chance",
		"Mysterious Employer",
		"Mythology Gag",
		"Narrator All Along",
		"Naughty Birdwatching",
		"Near Death Clairvoyance",
		"Near Death Experience",
		"Necessary Fail",
		"Needle in a Stack of Needles",
		"Never Split the Party",
		"Newspaper Dating",
		"Niche Network",
		"No Fourth Wall",
		"No MacGuffin No Winner",
		"Detente Comrade",
		"Eaten The MacGuffin",
		"Non-Sequitur",
		"Noodle Incident",
		"No Party Like A Donner Party",
		"Notable Non-Sequitur",
		"Not A Date",
		"Not Afraid Of You Anymore",
		"Not As You Know Them",
		"Not Cheating Unless You Get Caught",
		"Not Helping Your Case",
		"Not Important To This Episode Camp",
		"Not In Front Of The Parrot",
		"Not In My Contract",
		"Not My Driver",
		"Not My Lucky Day",
		"The Not Secret",
		"Not What It Looks Like",
		"Not What I Signed On For",
		"Obfuscating Stupidity",
		"Oblivious Adoption",
		"Oblivious Guilt Slinging",
		"Offered The Crown",
		"Offhand Backhand",
		"Offing the Offspring",
		"Off To Boarding School",
		"Oh Cisco",
		"Olaf's Hammer",
		"Ominous Multiple Screens",
		"Omni Impotence",
		"One Degree of Separation",
		"One Judge To Rule Them All",
		"One Side Of The Story",
		"One Way Trip",
		"Only Cool People Matter",
		"Only The Knowledgable May Pass",
		"Only Smart People May Pass",
		"Only The Worthy May Pass",
		"Orphan's Ordeal",
		"Orphan's Plot Trinket",
		"Orphean Rescue",
		"Or Was It A Dream?",
		"Out Giving Birth, Back in Two Minutes",
		"Out-of-Clothes Experience",
		"Overcome Their Differences",
		"Overly-Long Gag",
		"Padding",
		"Pandeism",
		"Parental Favoritism",
		"Party Scheduling Gambit",
		"Passed Over Promotion",
		"Pater Familicide",
		"Pay Phone",
		"Penultimate Outburst",
		"People Jars",
		"Permission to Speak Freely",
		"Perpetual Poverty",
		"Perspective Magic",
		"Perspective Reversal",
		"Perverted Sniffing",
		"Phlebotinum Battery",
		"Phone Booth",
		"Pick on Someone Your Own Species",
		"Pinocchio Syndrome",
		"Playing Both Sides",
		"Playing Nice For Now",
		"Playing Sick",
		"Plot Coupon",
		"Plot Detour",
		"Plot Device",
		"Plot-Driven Breakdown",
		"Plot Parallel",
		"Plot Technology",
		"Plummet Perspective",
		"Poison And Cure Gambit",
		"Poisoned Chalice Switcheroo",
		"Police Are Useless",
		"Poor Communication Kills",
		"Portal Pool",
		"Porn Stash",
		"Posthumous Character",
		"Powder Keg Crowd",
		"Power Fantasy",
		"Practical Voice Over",
		"Premature Eulogy",
		"Press Ganged",
		"Pressure Point",
		"Priceless Paperweight",
		"Princess For A Day",
		"Promoted To Scapegoat",
		"Protocol Peril",
		"Pseudo Crisis",
		"Psychological Horror",
		"Puberty Superpower",
		"The Public Domain Channel",
		"Public Execution",
		"Punk In The Trunk",
		"The Purge",
		"Put Down Your Gun And Step Away",
		"Put Me In, Coach!",
		"Rage Against the Author",
		"Rage Against The Mentor",
		"Rash Equilibrium",
		"Read the Freaking Manual",
		"Reality Bleed",
		"Rear Window Witness",
		"Red Herring Twist",
		"Regular Caller",
		"Reincarnation",
		"Reincarnation Romance",
		"Relationship Reboot",
		"Relationship-Salvaging Disaster",
		"Religious Russian Roulette",
		"Remake Cameo",
		"Remember When You Blew Up A Sun?",
		"Required Spinoff Crossover",
		"Rescue Romance",
		"Resurrected Romance",
		"Retcon",
		"Revision",
		"Rewrite",
		"Rewarded as a Traitor Deserves",
		"Rhetorical Request Blunder",
		"Ribbon Cutting Ceremony",
		"Right Hand Versus Left Hand",
		"Right On The Tick",
		"Right Place, Right Time, Wrong Reason",
		"Ripped from the Headlines",
		"Ripped From The Phone Book",
		"Road Show",
		"Rock Bottom",
		"Romantic Resolutions",
		"Room Disservice",
		"Rules of Orphan Economics",
		"Sadistic Choice",
		"Sarcasm Failure",
		"Scene Transition",
		"Scheherezade Gambit",
		"Schmuck Banquet",
		"Science Is Bad",
		"Science Is Wrong",
		"School Play",
		"Screaming Birth",
		"Screw Destiny",
		"Scully Syndrome",
		"Scylla and Charybdis",
		"Sealed Evil in a Duel",
		"Second Hand Storytelling",
		"Second Place Is For Winners",
		"Second Prize",
		"Secret Identity",
		"Secret Legacy",
		"Secret Path",
		"Secret Test of Character",
		"Seeking Sanctuary",
		"Send Me Back",
		"Sequel Reset",
		"Serious Business",
		"Set a Mook to Kill a Mook",
		"Shamed By A Mob",
		"Shameful Strip",
		"Shaming The Mob",
		"Shape Shifting",
		"Sharing a Body",
		"Shell Game",
		"Shock Collar",
		"Short Cuts Make Long Delays",
		"Short Distance Phone Call",
		"Shower of Angst",
		"Show Within a Show",
		"Shut Up, Hannibal!",
		"Silly Rabbit, Idealism Is for Kids!",
		"Silly Rabbit, Romance Is for Kids!",
		"Sliding Scale Of Plot Versus Characters",
		"Slippery Soap",
		"Slobs Versus Snobs",
		"Slow Clap",
		"Slumber Party",
		"Slumber Party Ploy",
		"Small Town Rivalry",
		"Smart Ball",
		"Smite Me, O Mighty Smiter",
		"Sneaky Departure",
		"Snooping Little Kid",
		"Snowball Lie",
		"Snowed In",
		"Somebody Set Up Us The Bomb",
		"Something Only They Would Say",
		"So Much For Stealth",
		"Sorkin Relationship Moment",
		"Sorry To Interrupt",
		"Sound Stone",
		"Sour Supporter",
		"Speak Friend And Enter",
		"Speak of the Devil",
		"Speed Dating",
		"Stable Time Loop",
		"Staring Contest",
		"Starts With A Suicide",
		"Starts With Their Funeral",
		"Status Quo Game Show",
		"Stay On The Path",
		"Staying With Friends",
		"Stock Femur Bone",
		"Stolen Good, Returned Better",
		"Stopped Clock",
		"Stuff Blowing Up",
		"Stuffed Into A Locker",
		"Stuffed Into A Trashcan",
		"Suckiness Is Painful",
		"Sudden Videogame Moment",
		"Sugary Malice",
		"Suicidal Cosmic Temper Tantrum",
		"Summoning Ritual",
		"Super Detailed Fight Narration",
		"Supernatural Aid",
		"Supernaturally Delicious and Nutritious",
		"Supporting Protagonist",
		"The Ishmael",
		"Survivalist Stash",
		"Survived The Beginning",
		"Suspended Animation",
		"Suspiciously Specific Sermon",
		"Sweet Polly Oliver",
		"Switched at Birth",
		"Sympathetic POV",
		"Talking In Bed",
		"Take a Third Option",
		"Take Over the World",
		"Tap on the Head",
		"Team Rocket Wins",
		"Team Spirit",
		"Televised Torture",
		"Temporal Paradox",
		"Temporary Blindness",
		"Temporary Love Interest",
		"Tempting Fate",
		"Ten Minutes in the Closet",
		"Tied Together Shoelace Trip",
		"There Is No Try",
		"These Questions Three",
		"The Tape Knew You Would Say That",
		"The Thing That Would Not Leave",
		"They Would Cut You Up",
		"Things Get Real",
		"Think Happy Thoughts",
		"Thinks Like a Romance Novel",
		"This Is My Story",
		"This Is As Far As I Go",
		"This Is Something He's Got To Do Himself",
		"This Is Your Brain On Evil",
		"This Means War!",
		"Three Act Structure",
		"Thrown Down A Well",
		"Thwarted Escape",
		"Time Travel",
		"Tomato Surprise",
		"Tongue Tied",
		"Total Eclipse of the Plot",
		"To the Pain",
		"Tragic Mistake",
		"Trap Door",
		"Trap Door Fail",
		"Trap Is The Only Option",
		"Transformation Ray",
		"The Treachery Of Images",
		"Treasure Map",
		"Troll Bridge",
		"Trust Password",
		"Twisted Echo Cut",
		"Two Girls and a Guy",
		"Two Guys and a Girl",
		"2 + Torture = 5",
		"Two Scenes One Dialogue",
		"Two Timer Date",
		"Unbalanced By Rival's Kid",
		"Uncle Herbie",
		"Un-Confession",
		"Unexpected Inheritance",
		"Unexpected Positive",
		"Unfamiliar Ceiling",
		"Unhand Them, Villain!",
		"Unperson",
		"Unsafe Haven",
		"Unseen Audience",
		"Unspoken Plan",
		"Unusually Uninteresting Name",
		"Using You All Along",
		"Victory Guided Amnesia",
		"Video Wills",
		"Villain Ball",
		"Villain Exit Stage Left",
		"Virus Misnomer",
		"Vision Quest",
		"Visions of Another Self",
		"Volleying Insults",
		"Wacky Wayside Tribe",
		"Waking Up At The Morgue",
		"Washington DC Invasion",
		"Watching Troy Burn",
		"We ARE Struggling Together",
		"We Are Team Cannon Fodder",
		"We Come in Peace  Shoot to Kill",
		"Wedding Day",
		"We Haven't Learned Anything Yet",
		"Welcome to the Big City",
		"We Need To Get Proof",
		"We Really Do Care",
		"We Should Get Another Tape",
		"What Year Is This?",
		"When The Clock Strikes Twelve",
		"\"Where Are They Now?\" Epilogue",
		"Where It All Began",
		"Who Needs Enemies?",
		"Who Will Bell The Cat",
		"Why Isn't It Attacking?",
		"Wild Teen Party",
		"Will",
		"Windows Of The Soul",
		"With a Friend and a Stranger",
		"With Due Respect",
		"Witness Protection",
		"The World Is Always Doomed",
		"World of Silence",
		"The Worst Seat In The House",
		"Wrecked Weapon",
		"Write Back to the Future",
		"Writer's Block",
		"Writing Lines",
		"Written-In Absence",
		"Wrong Wire",
		"Xanatos Gambit",
		"Xanatos Roulette",
		"Yellow Sash of Power",
		"You ALL Share My Story",
		"You Are Better Than You Think You Are",
		"You Are Grounded",
		"You Are in Command Now",
		"You Are The New Trend",
		"You Can Keep Her",
		"You Can't Fight Fate",
		"You Can't Go Home Again",
		"You Can't Thwart Stage One",
		"You Don't Want To Catch This",
		"You Don't Want To Die A Virgin, Do You?",
		"You Killed My Father",
		"You Know Who Said That?",
		"You Were Trying Too Hard",
		"You Will Be Beethoven",
		"You Would Make a Great Model",
		"Zero Sum Game"
	],
	character: [
		"Always Female",
		"Always Male",
		"Cops and Detectives",
		"Elders",
		"Heroes",
		"Hired Guns",
		"Western Characters",
		"Loser Archetype",
		"Love Interests",
		"Mentors",
		"Schoolteachers",
		"Normal People",
		"Occupation Tropes",
		"Seekers",
		"Seers",
		"Stock British Characters",
		"Stock Japanese Characters",
		"The Stoic",
		"Tricksters",
		"Con Man",
		"Villains",
		"Youngsters",
		"Absent-Minded Professor",
		"Accidental Pervert",
		"Agent Mulder",
		"Agent Scully",
		"Ambulance Chaser",
		"Angry Black Man",
		"Animal Stereotypes",
		"Apron Matron",
		"Arab Oil Sheikh",
		"Asian Storeowner",
		"Ax Crazy",
		"Badass",
		"Badass Normal",
		"Barbarian Tribe",
		"The Barber",
		"The Bard",
		"The Bartender",
		"Battle Butler",
		"The Berserker",
		"Best Served Cold",
		"Big Eater",
		"Blood Knight",
		"Bounty Hunter",
		"Bridezilla",
		"Brotherhood Of Funny Hats",
		"Bruce Lee Clone",
		"Bumbling Dad",
		"Bumbling Sidekick",
		"Bunny-Ears Lawyer",
		"The Caligula",
		"The Care Taker",
		"The Casanova",
		"The Charmer",
		"Chatty Hairdresser",
		"The Cheerleader",
		"Chick Magnet",
		"Chivalrous Pervert",
		"Chuck Yeager",
		"Church Militant",
		"City Mouse",
		"Class Clown",
		"Classically Trained Extra",
		"Cloudcuckoolander",
		"The Confidant",
		"Control Freak",
		"Cop Boyfriend",
		"The Coroner",
		"Cosmic Plaything",
		"Costumed Nonsuper Hero",
		"Covert Pervert",
		"Cowboy Cop",
		"Cranky Neighbor",
		"Crazy Awesome",
		"Crazy Survivalist",
		"Creepy Mortician",
		"Creepy Twins",
		"The Creepy Undertaker",
		"Crooked Contractor",
		"Crossdresser",
		"Creepy Crossdresser",
		"Crouching Moron, Hidden Badass",
		"Crusty Caretaker",
		"Cute Bruiser",
		"Cute Mute",
		"Cute Sports Club Manager",
		"Cutesy Dwarf",
		"Da Chief",
		"Dad The Veteran",
		"Da Editor",
		"Damsel Errant",
		"Dark Messiah",
		"Dark Skinned Redhead",
		"Death Seeker",
		"Deceptive Disciple",
		"Defector from Decadence",
		"Defrosting Ice Queen",
		"Depraved Dentist",
		"Determinator",
		"Determined Widow",
		"Directionless Driver",
		"Dirty Coward",
		"The Ditz",
		"Brainless Beauty",
		"Genius Ditz",
		"Idiot Savant",
		"Upper Class Twit",
		"Dogged Nice Guy",
		"Doting Parent",
		"Double Agent",
		"Drill Sergeant Nasty",
		"Dr. Jerk",
		"The Eeyore",
		"Enigmatic Empowering Entity",
		"Erudite Stoner",
		"Ethnic Magician",
		"The Everyman",
		"Evil Matriarch",
		"Face of a Thug",
		"Fake Ultimate Hero",
		"Farmer's Daughter",
		"Fat, Sweaty Southerner in a White Suit",
		"Femme Fatale",
		"The Fighting Narcissist",
		"The Flapper",
		"Foreign Fanservice",
		"Forest Ranger",
		"Gadgeteer Genius",
		"Gender Bender",
		"Glory Hound",
		"Glory Seeker",
		"Gold Digger",
		"Gonk",
		"Grande Dame",
		"Handsome Lech",
		"Half-Human Hybrid",
		"Half-Identical Twins",
		"Hardboiled Detective",
		"Heavy Sleeper",
		"The Hermit",
		"Honest John's Dealership",
		"House Husband",
		"Ignorant Of Their Own Ignorance",
		"The Informant",
		"Jewish Mother",
		"Kindly Housekeeper",
		"The Klutz",
		"Know-Nothing Know-It-All",
		"Landlord",
		"Cranky Landlord",
		"Single Issue Landlord",
		"Lethal Chef",
		"Literal-Minded",
		"Little Jimmy",
		"Living Legend",
		"Loony Fan",
		"Lovable Sex Maniac",
		"Lower Class Lout",
		"Lust Object",
		"Luvvies",
		"Masked Luchador",
		"Master Swordsman",
		"Mayor Pain",
		"Miles Gloriosus",
		"Mysterious Waif",
		"Narcissist",
		"The Nicknamer",
		"Not With Them For The Money",
		"One of the Boys",
		"One Note Cook",
		"Open Minded Parent",
		"Outside Man, Inside Man",
		"Person of Mass Destruction",
		"Pervert Dad",
		"Pintsized Powerhouse",
		"Plucky Office Girl",
		"Proud Warrior Race Guy",
		"Psycho Supporter",
		"Renaissance Man",
		"Replacement Goldfish",
		"The Rival",
		"The Rock Star",
		"Romantic Runner Up",
		"School Nurse",
		"Self-Made Man",
		"Serial Romeo",
		"Sexbot",
		"The Shrink",
		"Sickly Neurotic Geek",
		"Sleazy Politician",
		"Southern Belle",
		"Spirited Competitor",
		"Staff Chick",
		"Stage Magician",
		"Standard '50s Father",
		"Starving Artist",
		"Starving Student",
		"Strange Girl",
		"Strange Pond Woman",
		"Supreme Chef",
		"Tall, Dark, and Handsome",
		"Third-Person Person",
		"Tomboy",
		"Ugly Cute",
		"Unsatisfiable Customer",
		"Unstoppable Mailman",
		"Wandering Minstrel",
		"White Collar Worker",
		"Willing Channeler",
		"Winged Humanoid",
		"World's Strongest Man",
		"Young Future Famous People"
	],
	plot: [
		"Mystery Arc",
		"Romance Arc",
		"Romance Novel Plots",
		"The Hero's Journey",
		"Time Travel Tropes",
		"Truth and Lies",
		"Accidental Athlete",
		"Accidental Hero",
		"Accidental Marriage",
		"Achilles in His Tent",
		"Action Hero Babysitter",
		"Adventure Rebuff",
		"Adventures In The Bible",
		"Alien Invasion",
		"All for Nothing",
		"All That Glitters",
		"All Your Base Are Belong to Us",
		"Alternate Universe",
		"America Saves the Day",
		"Amnesia Danger",
		"And Now You Must Marry Me",
		"Animal Athlete Loophole",
		"Animal Testing",
		"Annoying Patient",
		"Antagonist In Mourning",
		"Anticlimactic Parent",
		"Appease The Volcano God",
		"Assimilation Plot",
		"Attack Of The Town Festival",
		"Axes At School",
		"The B Grade",
		"Bachelor Auction",
		"Back to School",
		"Bad Luck Charm",
		"Bad Samaritan",
		"Bad Santa",
		"Badass in Distress",
		"The Bard On Board",
		"Baseball Episode",
		"Bathe Her and Bring Her to Me",
		"Batman In My Basement",
		"Beach Episode",
		"Beauty Contest",
		"Be Careful What You Wish For",
		"Becoming the Costume",
		"Becoming the Mask",
		"Be Yourself",
		"Billy Elliot Plot",
		"Big Lipped Alligator Moment",
		"Body Count Competition",
		"Body Horror",
		"Body Snatcher",
		"Body Surf",
		"Boot Camp Episode",
		"The Boxing Episode",
		"Brainwashed",
		"Brainwashed and Crazy",
		"Breaking Out The Boss",
		"The Bride With A Past",
		"Bring News Back",
		"Bring It Back Alive",
		"Broken Masquerade",
		"Broken Pedestal",
		"Broken Streak",
		"Broken Treasure",
		"Brought Down to Badass",
		"Brought Down to Normal",
		"Bruce Wayne Held Hostage",
		"Bulk Buy Only",
		"Bury Me Not On The Lone Prairie",
		"Business As Unusual",
		"Busman's Holiday",
		"But I Can't Be Pregnant!",
		"Cabin Fever",
		"Cain and Abel",
		"The Cake Is a Lie",
		"The Caper",
		"Caper Rationalization",
		"Can't Get In Trouble For Nuthin'",
		"Captured Super Entity",
		"Cattle Drive",
		"Celebrity Is Overrated",
		"Celebrity Lie",
		"Celebrity Star",
		"Changing of the Guard",
		"Chain of Deals",
		"Character Focus",
		"Charlie and the Chocolate Parody",
		"The Chase",
		"Chased by Angry Natives",
		"Clean Up The Town",
		"Childhood Memory Demolition Team",
		"Children Raise You",
		"Cinderella Circumstances",
		"City in a Bottle",
		"Class Reunion",
		"Clear My Name",
		"Clear Their Name",
		"Clip Show",
		"Closed Circle",
		"Code Silver",
		"Cold Equation",
		"The Collector",
		"Color Me Black",
		"Comic Books Are Real",
		"Coming Out Story",
		"Have You Tried Not Being A Monster?",
		"Common Nonsense Jury",
		"Compromising Memoirs",
		"The Con",
		"Consolation World Record",
		"Contagious Powers",
		"Contract On The Hitman",
		"The Convenient Store Next Door",
		"Cooking Duel",
		"Cosmetic Catastrophe",
		"Costumer",
		"Crapsack World",
		"Crash Course Landing",
		"Credit Card Plot",
		"Criminal Mind Games",
		"Crossing the Desert",
		"Cuckoo Nest",
		"Cutting the Knot",
		"Date Peepers",
		"Day In The Life",
		"A Day in the Limelight",
		"A Day in the Slimelight",
		"The Day Of Reckoning",
		"Deadly Game",
		"Deadly Graduation",
		"Deadly Upgrade",
		"Dead Pet Sketch",
		"Deal with the Devil",
		"Death In The Clouds",
		"Death Is A Sad Thing",
		"Death Takes A Holiday",
		"Dénouement Episode",
		"De-power",
		"Defector From Commie Land",
		"Deserted Island",
		"Despite The Plan",
		"Destructive Saviour",
		"Deus Exit Machina",
		"Die Hard on an X",
		"Digging To China",
		"Digital Piracy Is Evil",
		"Divide and Conquer",
		"Divided We Fall",
		"A Dog Ate My Homework",
		"Don't Go In The Woods",
		"Doomed Moral Victor",
		"Doorstop Baby",
		"Door To Door Episode",
		"Dork Horse Candidate",
		"Do They Know It's Christmas Time?",
		"Down the Rabbit Hole",
		"Driving Test",
		"Driving Question",
		"Duels Decide Everything",
		"Duel to the Death",
		"Dug In Deeper",
		"Easily Thwarted Alien Invasion",
		"Easter Bunny",
		"Egg Sitting",
		"Eigen Plot",
		"Empire With A Dark Secret",
		"Empty Quiver",
		"Endurance Duel",
		"End of an Age",
		"Enemy Mine",
		"The Epic",
		"Epic Race",
		"Epiphanic Prison",
		"Equivalent Exchange",
		"Escape from the Crazy Plaze",
		"Evasive Fight Thread Episode",
		"Everybody Must Get Stoned",
		"Everybody's Dead Dave",
		"Everything But The Girl",
		"The Evils of Free Will",
		"Evil Plan",
		"Eviler than Thou",
		"Evil Twin",
		"Evil Will Fail",
		"Exact Words",
		"Excellent Adventure",
		"Fable Remake",
		"Failed Audition Plot",
		"Fairest Of Them All",
		"Family Disunion",
		"Family Rivalry",
		"Fantastic Voyage Plot",
		"False Crucible",
		"Farewell My Friend",
		"Faustian Rebellion",
		"Fauxtastic Voyage",
		"Favouritism Flip Flop",
		"Fawlty Towers Plot",
		"Feud Episode",
		"Fever Dream Episode",
		"Fidelity Test",
		"Fight Clubbing",
		"Fighting For A Homeland",
		"Fifteen Minutes Of Fame",
		"Fight Dracula",
		"The Final Temptation",
		"Finding Judas",
		"Find the Cure",
		"Fish Out of Temporal Water",
		"Flatline Plotline",
		"Flower From The Mountaintop",
		"Flowers For Algernon Syndrome",
		"A Fool and His New Money Are Soon Parted",
		"Foreign Correspondent",
		"Forgiveness Requires Death",
		"Forgotten Anniversary",
		"Forgotten Birthday",
		"Forgot the Call",
		"For Science",
		"Free the Frogs",
		"A Friend in Need",
		"Frivolous Lawsuit",
		"From Beyond The Fourth Wall",
		"From Nobody to Nightmare",
		"Fully Absorbed Finale",
		"Fumbling The Gauntlet",
		"The Fun In Funeral",
		"Fundraiser Carnival",
		"The Game Never Stopped",
		"The Game Plays You",
		"Game Show Appearance",
		"Garage Band",
		"Garage Sale",
		"Geeky Glasses",
		"Gender Separated Ensemble Episode",
		"Generational Saga",
		"Genocide Backfire",
		"Get Back to the Future",
		"Ghost Ship",
		"Ghost Story",
		"Girls Behind Bars",
		"Girl's Night Out Episode",
		"Giving Radio To The Romans",
		"Gladiator Revolt",
		"Go Among Mad People",
		"God and Satan Are Both Jerks",
		"God For A Day",
		"Going Native",
		"Going to See the Elephant",
		"Golden Helmet Of Mambrino",
		"Gold Fever",
		"Gondor Calls for Aid",
		"Government Conspiracy",
		"Grand Finale",
		"Grand Theft Me",
		"Grass Is Greener",
		"Great Escape",
		"The Great Repair",
		"The Greatest Story Never Told",
		"Groundhog Day Loop",
		"Guarding The Portal",
		"Guess Who I'm Marrying?",
		"Guinness Episode",
		"Guise Will Be Guise",
		"Gym Class Rope Climb",
		"Halfway Plot Switch",
		"Happy Ending Massage",
		"Harbinger Of Impending Doom",
		"He Knows Too Much",
		"Headbutting Heroes",
		"Hell On Earth",
		"Her Code Name Was Mary Sue",
		"Hero For A Day",
		"Heroes Gone Fishing",
		"Heroic Rematch",
		"Hiccup Hijinks",
		"Hired To Hunt Yourself",
		"The Homeward Journey",
		"Horrible Camping Trip",
		"Hot for Student",
		"Hot Springs Episode",
		"Hourglass Plot",
		"House Inspection",
		"Hulk's Cooldown Hug Corollary",
		"Humanity On Trial",
		"Hyde And Seek",
		"Hyperlink Story",
		"Hypno Fool",
		"I Am Who?",
		"Identity Impersonator",
		"Impossible Mission",
		"In Another Man's Shoes",
		"Innocence Lost",
		"Innocent Bystander Series",
		"Inside a Computer System",
		"Intrepid Fictioneer",
		"In With The In Crowd",
		"Inadequate Inheritor",
		"Inept Aptitude Test",
		"Indy Ploy",
		"The Infiltration",
		"Instant Book Deal",
		"Invented Individual",
		"Intergenerational Friendship",
		"Intoxication Ensues",
		"Invisible Main Character",
		"Irritation Is the Sincerest Form of Flattery",
		"Isolation Despondency",
		"It's A Costume Party, I Swear",
		"It's A Wonderful Plot",
		"It's Personal",
		"I Will Find You",
		"I Wish It Were Real",
		"Jailbird Of Panama",
		"Jekyll and Hyde",
		"Jigsaw Puzzle Plot",
		"Journey to the Center of the Mind ",
		"Just Fine Without You",
		"Jackie Robinson Story",
		"Joker Jury",
		"Judgment Of Solomon",
		"Jumping Off the Slippery Slope",
		"The Jungle Opera",
		"Jury Of The Damned",
		"Just So Story",
		"Just Think of the Potential",
		"Kafka Komedy",
		"Kangaroo Court",
		"Kansas City Shuffle",
		"Keystone Army",
		"Kids Versus Adults",
		"Kill Me Now or Forever Stay Your Hand",
		"Killed To Uphold The Masquerade",
		"Kingmaker Scenario",
		"Kon Tiki Plot",
		"Kudzu Plot",
		"Last Fertile Region",
		"Last Starfighter",
		"Leave Your Quest Test",
		"Legion of Doom",
		"Like You Were Dying",
		"Little Kid Lover",
		"Live Action Escort Mission",
		"Live Episode",
		"Loan Sharks",
		"Locked Room Mystery",
		"Lonely At The Top",
		"Long Game",
		"Lost Wedding Ring",
		"Lottery of Doom",
		"Lottery Ticket",
		"Lotus-Eater Machine",
		"Love Triangle",
		"MacGuffin Escort Mission",
		"Macho Disaster Expedition",
		"Madden Into Misanthropy",
		"Made a Slave",
		"The Magic Comes Back",
		"The Magic Goes Away",
		"The Magnificent Seven Samurai",
		"Mail Order Bride",
		"Maintain The Lie",
		"Make The Bear Angry Again",
		"Make Up Or Break Up",
		"The Makeover",
		"Making The Masterpiece",
		"Malignant Plot Tumor",
		"Mall Santa",
		"Mandatory Unretirement",
		"Manufacturing Victims",
		"Man In The Iron Mask",
		"Mary Sue Classic",
		"Masquerade Ball",
		"May The Farce Be With You",
		"Me's A Crowd",
		"The Migration",
		"Minor Crime Reveals Major Plot",
		"Miss Conception",
		"Mission from God",
		"Mistaken for Index",
		"Monster Is a Mommy",
		"Monster Protection Racket",
		"More than Mind Control",
		"The Moving Experience",
		"Moving The Goal Posts",
		"Mundanization",
		"My Biological Clock Is Ticking",
		"My Death Is Just the Beginning",
		"Nasty Party",
		"Never Learned To Read",
		"Never Lend To A Friend",
		"New Job Episode",
		"New Super Power",
		"Nitro Express",
		"No Antagonist",
		"No Doubt The Years Have Changed Me",
		"No Guy Wants An Amazon",
		"No Plot? No Problem!",
		"No Sympathy",
		"Not Himself",
		"Not So Imaginary Friend",
		"Oddly Common Rarity",
		"Off The Wagon",
		"An Offer You Can't Refuse",
		"Older Hero Vs Younger Villain",
		"One of Our Own",
		"One Born Every Minute",
		"On The Money",
		"Origins Issue",
		"Orphean Rescue",
		"Parent Trap Plot",
		"Parents For A Day",
		"Passed Over Inheritance",
		"Passed Over Promotion",
		"Passion Play",
		"Peer Pressure Makes You Evil",
		"Penny Among Diamonds",
		"People Zoo",
		"Pet Baby Wild Animal",
		"Pick Up Babes With Babes",
		"Picture Day",
		"Pirate Booty",
		"Plague of Good Fortune",
		"Playing Both Sides",
		"Playing Cyrano",
		"Playing Sick",
		"Plot Detour",
		"Plot Driving Secret",
		"Plot Leveling",
		"Plot Line Crossover",
		"Plot With Porn",
		"Poison And Cure Gambit",
		"Pony Tale",
		"Poorly Disguised Pilot",
		"Porn Without Plot",
		"Portal Book",
		"Post Robbery Trauma",
		"Predatory Business",
		"Premature Empowerment",
		"Premiere",
		"Everyone Meets Everyone",
		"One We Prepared Earlier",
		"Welcome Episode",
		"Pride Before A Fall",
		"Princess For A Day",
		"Protect This House",
		"Pursuing Parental Perils",
		"Putting the Band Back Together",
		"Prodigal Family",
		"The Promised Land",
		"Property Line",
		"Protagonist Journey To Villain",
		"Push Polling",
		"Pygmalion Plot",
		"Pygmalion Snap Back",
		"The Quest",
		"Quest for Identity",
		"Quest For The Rest",
		"Race Against The Clock",
		"Radio Contest",
		"Radish Cure",
		"Rage Against the Heavens",
		"Rage Within The Machine",
		"Rags to Royalty",
		"Random Events Plot",
		"Ransacked Room",
		"Rashomon Style",
		"Reactionary Fantasy",
		"Read The Fine Print",
		"A Real Man Is A Killer",
		"Really Seventeen Years Old",
		"Real World Episode",
		"Rear Window Investigation",
		"Rear Window Witness",
		"Reassignment Backfire",
		"Redemption Quest",
		"Reluctant Retiree",
		"Rescue Arc",
		"Revealing Coverup",
		"Revenge Of The Nerd",
		"Rightful King Returns",
		"Rip Van Winkle",
		"Faked Rip Van Winkle",
		"River Of Insanity",
		"Rise of Zitboy",
		"Roaring Rampage of Rescue",
		"Roaring Rampage of Revenge",
		"Road Trip Romance",
		"Robinsonade",
		"Rogue Juror",
		"RPG Episode",
		"Run For The Border",
		"Safety Worst",
		"Satchel Switcheroo",
		"Save Our Students",
		"Save Your Deity",
		"Saving Christmas",
		"Saving The Orphanage",
		"Scare Dare",
		"Scarecrow Solution",
		"Scarpia Ultimatum",
		"Scary Surprise Party",
		"School For Scheming",
		"Schrödinger's Butterfly",
		"Science Is Useless",
		"Scooby-Doo Hoax",
		"Screw the Rules, I'm Doing What's Right",
		"Season Finale",
		"Secret Diary",
		"Secret Relationship",
		"Selective Enforcement",
		"Send In The Search Team",
		"Separated at Birth",
		"Sex As Rite-Of-Passage",
		"Sex for Services",
		"Serial Killer",
		"Sex Equals Love",
		"Sexy Man Instant Harem",
		"Shaggy Dog Story",
		"ShapeShifting",
		"The Show Must Go On",
		"Sidekick Glass Ceiling",
		"The Siege",
		"A Simple Plan",
		"Single Episode Handicap",
		"Sinking Ship Scenario",
		"Sink or Swim Fatherhood",
		"Sleep Learning",
		"Snipe Hunt",
		"Snowed In",
		"Soap Opera Justice",
		"The So-Called Coward",
		"Something Completely Different",
		"A Day at the Bizarro",
		"The Documentary",
		"Lower Deck Episode",
		"Musical Episode",
		"Parody Episode",
		"Storybook Episode",
		"Spot the Imposter",
		"Sorcerer's Apprentice Plot",
		"Souvenir Land",
		"Speed Dating",
		"Spelling Bee",
		"Split And Reunion",
		"Stab The Salad",
		"Start My Own",
		"Start of Darkness",
		"Step Three: Profit",
		"Stone Soup",
		"Stranger in a Strange School",
		"Strangers On A Train Plot Murder",
		"Subverted Suspicion Aesop",
		"Succession Crisis",
		"Sudden Intelligence",
		"Suicide Mission",
		"Summon Everyman Hero",
		"Superhero Episode",
		"Superhero Origin",
		"Super Powers For A Day",
		"Suspiciously Similar Outfit",
		"Tag Along Actor",
		"Tag Team Suicide",
		"Taking Over The Town",
		"Talent Contest",
		"Talking Your Way Out",
		"The Taxi",
		"Teach Him Anger",
		"Technician Versus Performer",
		"Ten Little Murder Victims",
		"Thank You Mister Evil",
		"Their First Time",
		"There's No Place Like Home",
		"This Looks Like A Job For Aquaman",
		"Thriller On The Express",
		"Through the Eyes of Madness",
		"Time To Move",
		"Time Travel Escape",
		"Time Travel Romance",
		"To Hell and Back",
		"The Tonsillitis Episode",
		"Tontine",
		"Too Many Cooks Spoil The Soup",
		"Tournament Arc",
		"Town Contest Episode",
		"Train Job",
		"Training Accident",
		"Training the Peaceful Villagers",
		"Trainwreck Episode",
		"Trapped in the Past",
		"Trapped In TV Land",
		"Treasure Map",
		"Trend Aesop",
		"Trouble Follows You Home",
		"Troublemaking New Pet",
		"Turned Against Their Masters",
		"Turn In Your Badge",
		"Twelfth Night Adventure",
		"Twin Switch",
		"Two Timer Date",
		"Unlocking The Talent",
		"Untrusting Community",
		"Unwanted Rescue",
		"Embarrassing Rescue",
		"Unwanted Revival",
		"Utopia Justifies the Means",
		"Vampire Refugee",
		"Vanishing Village",
		"Very False Advertising",
		"Very Special Episode",
		"Too Smart For Strangers",
		"Villain Episode",
		"Visit By Divorced Dad",
		"Wake Up, Go to School, Save the World",
		"War for Fun and Profit",
		"Wayback Trip",
		"Wedding Day",
		"Well Intentioned Replacement",
		"We Need To Get Proof",
		"We Want Our Jerk Back",
		"We Would Have Told You, But...",
		"What Could Possibly Go Wrong?",
		"\"What Do They Fear?\" Episode",
		"Who Will Take The Kids?",
		"Whodunnit To Me",
		"Whole Plot Reference",
		"Witch Hunt",
		"Working The Same Case",
		"Wounded Gazelle Gambit",
		"Police Brutality Gambit",
		"Wounded Gazelle Warcry",
		"World Limited to the Plot",
		"Wrong Time-Travel Savvy",
		"Xanatos Gambit",
		"Xanatos Roulette",
		"Xanatos Speed Chess",
		"Xtreme Sport Xcuse Plot",
		"Yellow Brick Road",
		"You Already Changed The Past",
		"You Are Grounded",
		"You Can Keep Her",
		"You Go Girl",
		"You Have Waited Long Enough",
		"You Know What You Did",
		"You Wake Up in a Room",
		"You Would Make a Great Model",
		"Your Cheating Heart",
		"Your Worst Nightmare",
		"Yoyo Plot Point",
		"Zany Scheme",
		"Counter Zany",
		"Zany Scheme Chicken",
		"The Zotz",
		"Fish out of Water",
		"Alien Among Us",
		"Blithe Spirit",
		"Changeling Fantasy",
		"Rags to Riches",
		"Coming of Age Story",
		"Gotta Catch Them All",
		"Gotta Kill Them All",
		"Rock Opera Plot",
		"Set Right What Once Went Wrong",
		"Stern Chase",
		"Catch That Pigeon",
		"There Can Be Only One",
		"To Be a Master",
		"Vacation Episode",
		"Vampire Detective Series",
		"Victorious Loser",
		"Victory Is Boring",
		"Walking the Earth",
		"Water Source Tampering",
		"White Man's Burden",
		"Why Do You Hate The Dog?",
		"Withholding The Cure",
		"Wrong Turn At Albuquerque",
		"Wunza Plot",
		"You Are The New Trend",
		"Youngest Child Wins",
		"Youth Is Wasted On The Dumb",
		"Zombie Apocalypse",	
	]
};



